### ISSUE TITLE
Error when testing mta.py

### ISSUE THREAD

**Issue by seanykasp** [lightalan/subwayclock#11]
Im running into an issue when testin ./mta.py

I am receiving the following - are able to help point me in the right direction?

Traceback (most recent call last):
  File "./mta.py", line 180, in <module>
    print(getTrainTimes("Q03N","Q03S"))
  File "./mta.py", line 151, in getTrainTimes
    times = gettimes(f, ourUptownStation, ourDowntownStation)
  File "./mta.py", line 72, in gettimes
    response = requests.get(feed, headers=headers, timeout=30)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1285, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.7/http/client.py", line 1217, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufeff' in position 0: ordinal not in range(256)

**Comment by lightalan** [comment]
Check for obvious stuff:
Is your API KEY correct?
Are you behind a firewall (i.e. can you ping api-endpoint.mta.info)?
Try it again...it's possible the MTA API service was down at the time you
tried (not likely... but I've seen it before).

**Comment by seanykasp** [comment]
Hello Alan,

I am a complete noob here. How would I test ping an API endpoint with the
pi?

**Comment by lightalan** [comment]
Ahh.. it's pretty EZ

Just type:
ping api-endpoint.mta.info

**Comment by seanykasp** [comment]
I am able to ping the api endpoint.

It doesn't seem like the terminal is properly running the python script.

**Comment by lightalan** [comment]
Ok, looking more closely at your error output, it looks like you're getting
an error with a unicode character FEFF which is "zero-width unbreakable
space."
Double check there is nothing weird in your apikey, make sure the last
character in the apikey is the last character in the file.

**Comment by seanykasp** [comment]
So, I think that was it. I couldn’t get the mta.py file to open the
apikey.txt file so I just put the apikey directly on mta.py

I’m close. I just need to adjust the sizing.
